[window]
decorations = "full"
opacity = 0.85
title = "Alacritty"
dynamic_title = true
startup_mode = "Windowed"

  [window.dimensions]
  columns = 80
  lines = 24

  [window.padding]
  x = 12
  y = 12

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 12

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[colors.primary]
background = "#1a2621"
foreground = "#e8f0e3"

[colors.cursor]
text = "#1a2621"
cursor = "#5da247"

[colors.selection]
text = "#e8f0e3"
background = "#2d4734"

[colors.normal]
black = "#1a2621"
red = "#a54226"
green = "#5da247"
yellow = "#9c8726"
blue = "#2d4734"
magenta = "#6b735a"
cyan = "#3a785a"
white = "#e8f0e3"

[colors.bright]
black = "#334939"
red = "#d14f35"
green = "#7bc75f"
yellow = "#e5cd33"
blue = "#3d6046"
magenta = "#8a9673"
cyan = "#4b9972"
white = "#f4f9f0"

[cursor]
blink_interval = 750
unfocused_hollow = true

  [cursor.style]
  shape = "Block"
  blinking = "On"

[mouse]
hide_when_typing = true
